<?php
# This file was automatically generated by the MediaWiki 1.17.0
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename      = "MPA Robotics Wiki";
$wgMetaNamespace = "MPA_Robotics_Wiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath       = "/mediawiki";
$wgScriptExtension  = ".php";
$wgScript           = "$wgScriptPath/index.php";
$wgArticlePath 		= "/$1"; 
$wgUsePathInfo = true; 




## The relative URL path to the skins directory
$wgStylePath        = "$wgScriptPath/skins";

## The relative URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo             = "$wgScriptPath/skins/common/images/wiki.png";

## UPO means: this is also a user preference option

$wgEnableEmail      = true;
$wgEnableUserEmail  = true; # UPO

$wgEmergencyContact = "admin@team3926.org";
$wgPasswordSender   = "admin@team3926.org";

$wgEnotifUserTalk      = true; # UPO
$wgEnotifWatchlist     = true; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype           = "mysql";
$wgDBserver         = "mysql.team3926.org";
$wgDBname           = "mpawiki";
$wgDBuser           = "mpauser";
$wgDBpassword       = "turbomoustache";

# MySQL specific settings
$wgDBprefix         = "mpaMW";

# MySQL table options to use during installation or update
$wgDBTableOptions   = "ENGINE=MyISAM, DEFAULT CHARSET=utf8";

# Experimental charset support for MySQL 4.1/5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType    = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads  = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from http://commons.wikimedia.org
$wgUseInstantCommons  = true;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
#$wgHashedUploadDirectory = false;

## If you have the appropriate support software installed
## you can enable inline LaTeX equations:
$wgUseTeX           = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of ./languages/Language(.*).php
$wgLanguageCode = "en";

$wgSecretKey = "bf75a435ed1b0e2b32b7d1d1d462d4814a425185b5b297bd5f6da55fb098d1f4";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "2442bcdef0e7eb4d";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook', 'vector':
$wgDefaultSkin = "vector";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
#$wgEnableCreativeCommonsRdf = true;
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl  = "";
$wgRightsText = "";
$wgRightsIcon = "";
# $wgRightsCode = ""; # Not yet used

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";



# Query string length limit for ResourceLoader. You should only set this if
# your web server has a query string length limit (then set it to that limit),
# or if you have suhosin.get.max_value_length set in php.ini (then set it to
# that value)
$wgResourceLoaderMaxQueryLength = -1;


# End of automatically generated settings.
# Add more configuration options below.

#Sets group permissions
//Anon Privileges -- No access
$wgGroupPermissions['*']['createaccount']		= true;
$wgGroupPermissions['*']['read']				= false;
$wgGroupPermissions['*']['edit']				= false;
$wgGroupPermissions['*']['createpage']			= false;
$wgGroupPermissions['*']['createtalk']			= false;
$wgGroupPermissions['*']['upload']				= false;
$wgGroupPermissions['*']['editprotected']		= false;
$wgGroupPermissions['*']['writeapi']			= false;

//Everyone can access Home, login, and help pages
$wgWhitelistRead = array ( "Main Page", "Account Creation", "Special:Userlogin", "Help:Contents", "Special:UserLogout", "About Us", "MediaWiki:Common.css", 
"MediaWiki:Common.js", "MediaWiki:Monobook.css", "MediaWiki:Monobook.js", "-", "MediaWiki:Vector.css", "MediaWiki:Vector.js", "Special:Preferences", "Special:ConfirmEmail", "Special:Invalidateemail" );

#User Privileges -- No access until confirmed
$wgGroupPermissions['user']['read']				= false;
$wgGroupPermissions['user']['edit']				= false;
$wgGroupPermissions['user']['upload']			= false;
$wgGroupPermissions['user']['editprotected']	= false;
$wgGroupPermissions['user']['writeapi']			= false;
$wgGroupPermissions['user']['move']				= false;
$wgGroupPermissions['user']['move-subpages']	= false;
$wgGroupPermissions['user']['move-rootuserpages']	= false;
$wgGroupPermissions['user']['movefile']			= false;
$wgGroupPermissions['user']['reupload']			= false;
$wgGroupPermissions['user']['reuspload-shared']	= false;
$wgGroupPermissions['user']['purge']			= false;
$wgGroupPermissions['user']['sendemail']		= false;

$wgGroupPermissions['user']['createpage']		= false;
$wgGroupPermissions['user']['createtalk']		= false;
$wgGroupPermissions['user']['minoredit']		= false;
$wgGroupPermissions['user']['reupload-shared']	= false;

#Autoconfirmed Privilidges
$wgGroupPermissions['autoconfirmed']['autopatrol']	= true;

#Team Privileges
$wgGroupPermissions['Team']['read']				= true;
$wgGroupPermissions['Team']['edit']				= true;
$wgGroupPermissions['Team']['createpage']		= true;
$wgGroupPermissions['Team']['createtalk']		= true;
#$wgGroupPermissions['Team']['move']			= true;
$wgGroupPermissions['Team']['upload']			= true;
$wgGroupPermissions['Team']['reupload-own']		= true;
$wgGroupPermissions['Team']['minoredit']		= true;
$wgGroupPermissions['Team']['sendemail'] 		= true;
$wgGroupPermissions['Team']['reupload']			= true;

#Parent Privileges
$wgGroupPermissions['Parent']['read']			= true;
$wgGroupPermissions['Parent']['edit']			= true;
$wgGroupPermissions['Parent']['createpage']		= true;
$wgGroupPermissions['Parent']['createtalk']		= true;
#$wgGroupPermissions['Parent']['move']			= true;
$wgGroupPermissions['Parent']['upload']			= true;
$wgGroupPermissions['Parent']['reupload-own']	= true;
$wgGroupPermissions['Parent']['minoredit']		= true;
$wgGroupPermissions['Parent']['sendemail'] 		= true;
$wgGroupPermissions['Parent']['reupload']		= true;

#Mentor Privileges
$wgGroupPermissions['Mentor']['reupload']		= true;
$wgGroupPermissions['Mentor']['editprotected']	= true;
$wgGroupPermissions['Mentor']['delete']			= true;
$wgGroupPermissions['Mentor']['undelete']		= true;
$wgGroupPermissions['Mentor']['browsearchive']	= true;
$wgGroupPermissions['Mentor']['protect']		= true;
$wgGroupPermissions['Mentor']['block']			= true;
$wgGroupPermissions['Mentor']['blockemail']		= true;
$wgGroupPermissions['Mentor']['rollback']		= true;

$wgGroupPermissions['Mentor']['move']			= true;
$wgGroupPermissions['Mentor']['patrol']			= true;
$wgGroupPermissions['Mentor']['read']			= true;
$wgGroupPermissions['Mentor']['edit']			= true;
$wgGroupPermissions['Mentor']['createpage']		= true;
$wgGroupPermissions['Mentor']['createtalk']		= true;
$wgGroupPermissions['Mentor']['autopatrol']		= true;

$wgAddGroups['Mentor'] = array( 'Team', 'Mentor', 'Parent');
$wgRemoveGroups['Mentor'] = array( 'Team', 'Mentor', 'Parent');

#Additional Sysop Privileges to get around block
$wgGroupPermissions['sysop']['read']			= true;
$wgGroupPermissions['sysop']['edit']			= true;
$wgGroupPermissions['sysop']['upload']			= true;
$wgGroupPermissions['sysop']['move']			= true;
$wgGroupPermissions['sysop']['purge']			= true;
$wgGroupPermissions['sysop']['writeapi']		= true;
$wgGroupPermissions['sysop']['apihighlimits']	= true;
$wgGroupPermissions['sysop']['minoredit']		= true;
$wgGroupPermissions['sysop']['suppressrevision']	= true;
#$wgGroupPermissions['sysop']['userrights']  	= true;
$wgAddGroups['sysop'] = array( 'Team', 'Mentor', 'bot', 'Parent');
$wgRemoveGroups['sysop'] = array( 'Team', 'Mentor', 'bot', 'sysop', 'bureaucrat', 'Parent');

$wgAddGroups['sysop']['root'] 					= false;
$wgAddGroups['bureaucrat']['root'] 				= false;
$wgRemoveGroups['sysop']['root'] 				= false;
$wgRemoveGroups['bureaucrat']['root'] 			= false;
#$wgGroupPermissions['bureaucrat']['userrights']  	= false;
$wgAddGroups['bureaucrat'] = array( 'Team', 'Mentor', 'bot', 'bureaucrat', 'Parent');
$wgRemoveGroups['bureaucrat'] = array( 'Team', 'Mentor', 'bot', 'bureaucrat', 'Parent');

#$wgAddGroups['sysop']['checkuser'] 			= false;
#$wgAddGroups['bureaucrat']['checkuser'] 		= false;
#$wgRemoveGroups['sysop']['checkuser'] 			= false;
#$wgRemoveGroups['bureaucrat']['checkuser'] 	= false;
#$wgAddGroups['checkuser']['checkuser'] 		= true;
#$wgRemoveGroups['checkuser']['checkuser'] 		= true;

$wgGroupPermissions['root']['userrights'] 	 	= true;
$wgGroupPermissions['root']['read']			= true;
$wgGroupPermissions['root']['edit']			= true;
$wgGroupPermissions['root']['upload']			= true;
$wgGroupPermissions['root']['move']			= true;
$wgGroupPermissions['root']['purge']			= true;
$wgGroupPermissions['root']['writeapi']		= true;
$wgGroupPermissions['root']['apihighlimits']	= true;
$wgGroupPermissions['root']['minoredit']		= true;
$wgGroupPermissions['root']['suppressrevision']	= true;

#Don't touch without talking to Connor
###################################
###################################
##	 VOODOO CODE DO NOT TOUCH	 ##
###################################
###################################
$wgAutoConfirmCount = 2;
$wgDefaultUserOptions['timecorrection'] = '-06:00';
$wgLocaltimezone = "America/Chicago";
$oldtz = getenv("TZ");
putenv("TZ=$wgLocaltimezone");
# Versions before 1.7.0 used $wgLocalTZoffset as hours.
# After 1.7.0 offset as minutes
$wgLocalTZoffset = date("Z") / 60;
putenv("TZ=$oldtz");

//$wgUsePathInfo = true;
###################################
##	   	END VOODOO CODE			 ##
###################################



##########################
######EXTENSION CODE######
##########################

# Vector provides enhancements to the Vector skin

# This extension requires MediaWiki 1.17+ because it makes use of ResourceLoader.

# Example LocalSettings.php additions

require_once( "$IP/extensions/Vector/Vector.php" );

# Before configuring this extension, see Vector.php and become familiar with the initial state and structure of the
# $wgVectorFeatures configuration variable. Essentially it's an array of arrays, keyed by feature name, each containing
# global and user keys with boolean values. "global" indicates that it should be turned on for everyone always, while
# user indicates that users should be allowed to turn it on or off in their user preferences.

# To enable a preference by default but still allow users to disable it in preferences, use something like...

$wgDefaultUserOptions['vector-collapsiblenav'] = 1;

# By default, the Vector skin does not use the simplified search box. To take advantage of the simplesearch feature you
# must add this to your LocalSettings.php file.

$wgVectorUseSimpleSearch = true;


############################################
############################################


# WikiEditor provides enhancements to the MediaWiki edit page

# This extension requires MediaWiki 1.17+ because it makes use of ResourceLoader.

# Example LocalSettings.php additions

require_once( "$IP/extensions/WikiEditor/WikiEditor.php" );

# Before configuring this extension, see WikiEditor.php and become familiar with the initial state and structure of the
# $wgWikiEditorFeatures configuration variable. Essentially it's an array of arrays, keyed by feature name, each
# containing global and user keys with boolean values. "global" indicates that it should be turned on for everyone
# always, while user indicates that users should be allowed to turn it on or off in their user preferences.

# To enable a preference by default but still allow users to disable it in preferences, use something like...

$wgDefaultUserOptions['usebetatoolbar'] = 1;
$wgDefaultUserOptions['usebetatoolbar-cgd'] = 1;
$wgDefaultUserOptions['wikieditor-preview'] = 1;

##Wiki Configure Extension Rights

# Adding new rights...
$wgAvailableRights[] = 'configure';
$wgAvailableRights[] = 'configure-all';
$wgAvailableRights[] = 'configure-interwiki';
$wgAvailableRights[] = 'viewconfig';
$wgAvailableRights[] = 'viewconfig-all';
$wgAvailableRights[] = 'viewconfig-interwiki';
$wgAvailableRights[] = 'extensions';
$wgAvailableRights[] = 'extensions-all';
$wgAvailableRights[] = 'extensions-interwiki';

# Rights for Special:Configure
#$wgGroupPermissions['bureaucrat']['configure'] = true;
#$wgGroupPermissions['bureaucrat']['configure-interwiki'] = true;
#$wgGroupPermissions['bureaucrat']['configure-all'] = true;

# Rights for Special:Extensions
#$wgGroupPermissions['bureaucrat']['extensions'] = true;
# $wgGroupPermissions['bureaucrat']['extensions-interwiki'] = true;
# $wgGroupPermissions['developer']['extensions-all'] = true;

# Rights for Special:ViewConfig
#$wgGroupPermissions['sysop']['viewconfig'] = true;
# $wgGroupPermissions['sysop']['viewconfig-interwiki'] = true;
# $wgGroupPermissions['developer']['viewconfig-all'] = true;

#Fixed Rights

# Rights for Special:Configure
$wgGroupPermissions['root']['configure'] = true;

# Rights for Special:Extensions
$wgGroupPermissions['root']['extensions'] = true;

# Rights for Special:ViewConfig
$wgGroupPermissions['root']['viewconfig'] = true;

###############
###############

# Voting Rights #

##
#Make sure to run Vote.sql against database before enabling this extension
#Enable Voting
require_once("$IP/extensions/Vote/Vote.php");
##

/**
 * Users who can vote
 */
$wgGroupPermissions['Team']['vote'] = true;
$wgGroupPermissions['Mentor']['vote'] = true;
$wgGroupPermissions['Parent']['vote'] = false;

/**
 * Users who can view vote results
 */
$wgGroupPermissions['root']['voteadmin'] = true;

#################
#################
$wgStrictFileExtensions = false;
$wgVerifyMimeType = false;

$wgFileExtensions[] = 'doc';
$wgFileExtensions[] = 'xls';
$wgFileExtensions[] = 'pdf';
$wgFileExtensions[] = 'docx';
$wgFileExtensions[] = 'odt';
$wgFileExtensions[] = 'txt';
$wgFileExtensions[] = 'rtf';
$wgFileExtensions = array('png','gif','jpg','jpeg','doc','xls','pdf','ppt','tiff','bmp','docx', 'xlsx', 'pptx','odt','ods','odp','odg','svg','docx');



$wgMaxShellMemory = unlimited;
$wgMaxShellFileSize = unlimited;


#############DEBUG SETTINGS###################
$wgDebugLogFile         = $wgScriptPath.'wikilogs/wiki.log';
$wgDebugRedirects       = true;
$wgDebugComments        = true;
###############################################